#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Hour of Code

# Short bio or description (displayed in the header)
description: Every student should have the opportunity to learn Computer Science.
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://d13yacurqjgara.cloudfront.net/users/298864/screenshots/1653384/kw.png


categories: [Resources, Educator Notes]

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: katie@roachhd.com
  facebook: Code.org
  flickr: 
  github: roachhd/kids-code-hour
  instagram: 
  linkedin: 
  pinterest: roachhd
  rss: kidscodehour
  twitter: codeorg
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://roachhd.githib.io/kids-code-hour/feed.xml

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/kids-code-hour"

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

